apiVersion: batch/v1
kind: CronJob
metadata:
  name: decide-water
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rediswater
            image: localhost:32000/decide-water:0.08
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: hotf-config
          restartPolicy: OnFailure
