apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      #securityContext:
      #  runAsNonRoot: true
      #  runAsUser: 1000
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}
            image: docker-registry.docker-registry:32000/{{ .Release.Name }}:0.05
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: hotf-config
          restartPolicy: OnFailure
