apiVersion: batch/v1
kind: CronJob
metadata:
  name: calreadredis
  namespace: sensorredis
  labels:
    app: calreadredis
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: calreadredis
            image: localhost:32000/calread-redis:0.02
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: hotf-config
          restartPolicy: Never
