apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: docker-registry
  name: docker-registry
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 32000
    protocol: TCP
    nodePort: 32000
    targetPort: 32000
  selector:
    app: docker-registry
  type: NodePort
status:
  loadBalancer: {}
