apiVersion: apps/v1
kind: Deployment
metadata:
  name: processcal
  namespace: thermo
  labels:
    app: processcal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processcal
  template:
    metadata:
      labels:
        app: processcal
    spec:
      containers:
      - name: processcal
        image: localhost:32000/proc-cal
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIG_FILE
          value: "/data/pithermostat.conf"
        volumeMounts:
        - name: config-data
          mountPath: /data
      restartPolicy: IfNotPresent
      volumes:
      - name: config-data
        configMap:
          name: proctemps-config
          items: 
          - key: pithermostat.conf
            path: pithermostat.conf 
